### ISSUE TITLE
`getIndex`, `getPositionCode` and other related methods do not respect `IterationOrder`

### ISSUE THREAD

**Issue by soroushjp** [cheminfo/well-plates#8]
Firstly, thanks for creating and open-sourcing this great library.

One thing I do find strange is that there is the concept of an `IterationOrder` but this is not respected for key methods such as `getPositionCode` and `getIndex` which rely on an index. More obvious and expected behaviour (in my opinion as a package user in the scientific community) would be for `IterationOrder` to be respected everywhere there an index is provided.

Would you be open to a PR to change this behaviour? I could look into such a PR. For now, I'm working around this by using `getTransposedIndex` as a wrapper in a number of places, but this less than ideal.

**Comment by stropitek** [comment]
Hi, thanks for reaching out

Indeed you are right, it would make more sense if it affected indexing globally, rather than just the iterator.

I'm happy to assist / review if you create a PR

I would also be in favor of renaming the option from `iterationOrder` to `indexationOrder` or `indexOrder` then

**Comment by soroushjp** [comment]
Thanks for being open to this change @stropitek . I'll definitely make a PR as soon as I can, though it may take me a little while due to my present workload. Don't feel the need to wait for me if this is already on your agenda. If I do get started on this change, I will be sure to post here first to avoid duplicate work.
